name: quit_smoking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_svg: ^2.2.1
  http: ^1.5.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  syncfusion_flutter_charts: ^31.1.19
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
